import {test} from 'node:test';
import {randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
import {createApp} from '../server/app.mjs';
test('admin authorization, moderation, checkout exclusion, session revocation and audit',async()=>{
 const {app,db}=await createApp({databaseUrl:'',dbPath:':memory:',demo:true});
 const server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});
 const base=`http://127.0.0.1:${server.address().port}/api`;
 async function call(route,body,token){const r=await fetch(base+route,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,...await r.json()};}
 try {
  const admin=await call('/auth/register',{name:'Admin',email:'admin@example.com',password:'test-password'});
  const buyer=await call('/auth/register',{name:'Buyer',email:'buyer@example.com',password:'test-password'});
  assert.equal((await call('/admin/overview')).status,401);
  assert.equal((await call('/admin/overview',null,admin.token)).status,403);
  await db.prepare('INSERT INTO admin_roles(user_id) VALUES (?)').run(admin.user.id);
  assert.equal((await call('/admin/overview',null,admin.token)).status,200);
  for(const kind of ['users','shops','products','orders','jobs','audit'])assert.equal((await call('/admin/list/'+kind,null,admin.token)).status,200,kind);
  const features={productType:'Kazak',styles:['Minimal'],colors:['Krem'],contexts:['Günlük'],description:'Dokulu bir kazak.'};
  const vector=JSON.stringify(Array.from({length:768},(_,i)=>i===0?1:0));
  await db.prepare('INSERT INTO ai_cache(cache_key,features,embedding) VALUES (?,?::jsonb,?::vector)').run('old-analysis',JSON.stringify(features),vector);
  await db.prepare("INSERT INTO ai_jobs(id,product_id,cache_key,content_hash,status) VALUES (?,?,?,?,?)").run('completed-analysis','soft-knit','old-analysis','old-media','done');
  await db.prepare("INSERT INTO ai_jobs(id,product_id,cache_key,content_hash,status) VALUES (?,?,?,?,?)").run('pending-analysis','soft-knit','new-analysis','new-media','pending');
  await db.prepare("INSERT INTO product_features(product_id,content_hash,model_version,features) VALUES (?,?,?,?::jsonb)").run('soft-knit','new-media','new-model',JSON.stringify({...features,styles:['Different']}));
  assert.equal((await call('/admin/list/jobs')).status,401);
  assert.equal((await call('/admin/list/jobs',null,buyer.token)).status,403);
  const jobs=await call('/admin/list/jobs',null,admin.token);
  assert.deepEqual(jobs.items.find(j=>j.id==='completed-analysis').analysis,features);
  assert.equal(jobs.items.find(j=>j.id==='pending-analysis').analysis,null);
  assert.ok(jobs.items.find(j=>j.id==='completed-analysis').analyzed_at);
  assert.ok(!JSON.stringify(jobs).includes('embedding'));
  const filtered=await call('/admin/list/jobs?q=Minimal',null,admin.token);
  assert.deepEqual(filtered.items.map(j=>j.id),['completed-analysis']);
  assert.equal((await call('/admin/list/users?page=-1',null,admin.token)).status,400);
  const listing=await call('/admin/list/users',null,admin.token);assert.ok(!JSON.stringify(listing).includes('password'));
  const cmd={kind:'product',id:'soft-knit',disabled:true,reason:'Test moderation'};
  assert.equal((await call('/admin/moderate',cmd,buyer.token)).status,403);
  assert.equal((await call('/admin/moderate',{...cmd,reason:''},admin.token)).status,400);
  assert.equal((await call('/admin/moderate',cmd,admin.token)).status,200);
  assert.ok(!(await call('/products')).products.some(p=>p.id==='soft-knit'));
  assert.equal((await call('/checkout',{requestKey:randomUUID(),demoAcknowledged:true,address:'Test address for demo only',name:'Buyer',items:[{productId:'soft-knit',size:'S',quantity:1}]},buyer.token)).status,400);
  assert.equal((await call('/admin/moderate',{...cmd,disabled:false},admin.token)).status,200);
  assert.ok((await call('/products')).products.some(p=>p.id==='soft-knit'));
  assert.equal((await call('/admin/moderate',{kind:'user',id:admin.user.id,disabled:true,reason:'Test'},admin.token)).status,409);
  assert.equal((await call('/admin/moderate',{kind:'user',id:buyer.user.id,disabled:true,reason:'Test'},admin.token)).status,200);
  assert.equal((await call('/me',null,buyer.token)).status,401);
  assert.equal((await call('/auth/login',{email:'buyer@example.com',password:'test-password'})).status,403);
  assert.equal((await call('/admin/moderate',{kind:'user',id:'studio-m',disabled:true,reason:'Test'},admin.token)).status,200);
  assert.ok(!(await call('/products')).products.some(p=>p.sellerId==='studio-m'));
  const audits=await call('/admin/list/audit',null,admin.token);assert.equal(audits.items.length,4);
 }finally{await new Promise(r=>server.close(r));await db.close();}
});
