import { useEffect, useState } from 'react';
import { Pressable, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { useStore } from '../../lib/store';
import { Button, colors, ErrorText, Field, Page, styles } from '../../components/ui';
import { MessageCenter } from '../../features/Messages';
import { NotificationLink } from '../../components/NotificationLink';
import { EmailVerification } from '../../components/EmailVerification';
import SellerStudio from '../../features/SellerStudio';

export default function StudioWeb() {
  const params=useLocalSearchParams<{section?:string;conversationId?:string}>();
  const [section, setSection] = useState<'store' | 'messages'>('store');
  useEffect(()=>{if(params.section==='messages'){const timer=setTimeout(()=>setSection('messages'),0);return()=>clearTimeout(timer);}},[params.section,params.conversationId]);
  const { user, authenticate, logout, hydrated } = useStore(); const [mode, setMode] = useState<'login' | 'register'>('login'); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit() { setBusy(true); setError(''); try { await authenticate(mode, { name, email: email.trim(), password }); setPassword(''); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <View style={{ flex: 1, backgroundColor: colors.canvas }}><View style={{ height: 82, paddingHorizontal: 28, borderBottomWidth: 1, borderBottomColor: colors.line, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}><View style={styles.row}><Text style={{ color: '#FFF', fontSize: 29, fontWeight: '800', letterSpacing: -1.8 }}>swipe.</Text><Text style={{ color: colors.muted, fontSize: 12 }}>studio / mağaza paneli</Text></View><Pressable accessibilityRole="link" onPress={() => router.push('/')}><Text style={{ color: colors.muted, fontSize: 12 }}>Akışı aç ↗</Text></Pressable></View>
    {!hydrated ? <Page title="Yükleniyor…"><View /></Page> : !user ? <Page title="Mağazan burada büyüsün." subtitle="Profilini yönet, parçalarını paylaş. Hepsi web panelinde."><View style={{ maxWidth: 420, marginTop: 30, gap: 20 }}><View style={styles.row}>{(['login', 'register'] as const).map(value => <Pressable key={value} accessibilityRole="tab" accessibilityState={{ selected: value === mode }} onPress={() => { setMode(value); setError(''); }} style={{ paddingVertical: 10, borderBottomWidth: 1, borderColor: value === mode ? '#FFF' : 'transparent' }}><Text style={{ color: value === mode ? '#FFF' : '#888', fontSize: 14 }}>{value === 'login' ? 'Giriş yap' : 'Satıcı hesabı oluştur'}</Text></Pressable>)}</View>{mode === 'register' && <Field label="Ad soyad" value={name} onChangeText={setName} autoComplete="name" />}<Field label="E-posta" value={email} onChangeText={setEmail} autoCapitalize="none" autoComplete="email" keyboardType="email-address" /><Field label="Şifre" secureTextEntry value={password} onChangeText={setPassword} onSubmitEditing={submit} autoComplete={mode === 'register' ? 'new-password' : 'current-password'} /><ErrorText message={error} /><Button title={mode === 'login' ? 'Panele giriş yap' : 'Satıcı hesabımı oluştur'} loading={busy} onPress={submit} /><Button title="Şifremi unuttum" outline onPress={()=>router.push('/account/forgot-password')}/></View></Page> : <><View style={{ paddingHorizontal: 28, paddingTop: 15, flexDirection: 'row', justifyContent: 'flex-end' }}><Pressable accessibilityRole="button" accessibilityLabel="Studio oturumunu kapat" onPress={async () => { try { await logout(); } catch (e) { setError((e as Error).message); } }}><Text style={{ color: colors.muted, fontSize: 12 }}>{user.name} · Çıkış yap</Text></Pressable></View><View style={{paddingHorizontal:28}}><NotificationLink key={user.id}/><EmailVerification key={user.id}/></View><ErrorText message={error} />{user.shop && <View style={{ flexDirection: 'row', gap: 22, paddingHorizontal: 28, paddingVertical: 15 }}>{(['store', 'messages'] as const).map(value => <Pressable key={value} accessibilityRole="tab" accessibilityState={{ selected: section === value }} onPress={() => setSection(value)} style={{ paddingVertical: 12, borderBottomWidth: 2, borderColor: section === value ? '#FFF' : 'transparent' }}><Text style={{ color: section === value ? '#FFF' : colors.muted }}>{value === 'store' ? 'Mağazam' : 'Mesajlar'}</Text></Pressable>)}</View>}{section === 'messages' && user.shop ? <View style={{ flex: 1, maxWidth: 840, width: '100%', alignSelf: 'center' }}><MessageCenter seller conversationId={params.conversationId}/></View> : <SellerStudio />}</>}
  </View>;
}
