import { useCallback, useState } from 'react';
import { Pressable, Text, View } from 'react-native';
import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { useStore } from '../lib/store';
import { EmailVerification } from '../components/EmailVerification';
import { NotificationLink } from '../components/NotificationLink';
import { emptyShipping, shippingLabels } from '../../shared/shipping';
import { api } from '../lib/api';
import { money, Order } from '../../shared/types';
import { Button, colors, Empty, ErrorText, Field, Page, styles } from '../components/ui';
export default function Profile() {
  const { user, authenticate, logout, hydrated, resetFeed, setToast } = useStore(); const { next } = useLocalSearchParams<{ next?: string }>();
  const [mode, setMode] = useState<'login' | 'register'>('register'); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [orders, setOrders] = useState<Order[]>([]);
  useFocusEffect(useCallback(() => { let active = true; if (user) void api<{ orders: Order[] }>('/orders').then(data => { if (active) setOrders(data.orders); }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, [user]));
  async function submit() { setBusy(true); setError(''); try { await authenticate(mode, { email: email.trim(), password, name: name.trim() }); setPassword(''); if (next === 'checkout') router.replace('/checkout'); else if (next === '/messages' || /^\/messages\?productId=[a-zA-Z0-9%-]+$/.test(next || '')) router.replace(next as '/messages'); else if (/^\/social\/[a-zA-Z0-9-]+\?tab=(comments|reviews)$/.test(next || '')) router.replace(next as '/'); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  if (!hydrated) return <Page title="Hesabın yükleniyor…"><View /></Page>;
  return <Page title={user ? `Merhaba, ${user.name.split(' ')[0]}.` : 'Keşiflerin sana ait olsun.'} subtitle={user ? user.email : 'Beğendiklerin ve siparişlerin, hepsi sana ait.'}>
    <View style={{ flexDirection: 'row', gap: 12, marginTop: 24, flexWrap: 'wrap' }}><Button title="Beğendiklerin" icon="heart" outline onPress={() => router.push('/saved')} /><Button title="Takip ettiğin mağazalar" outline onPress={() => router.push('/following')} /><Button title="Mesajların" icon="send" outline onPress={() => router.push('/messages')} /></View>
    <View style={{ marginTop: 20, alignItems: 'flex-start' }}><Button title="Keşfet’i sıfırla" outline onPress={async () => { try { await resetFeed(); } catch (e) { setToast((e as Error).message); } }} /><Text style={[styles.subtitle, { marginTop: 8 }]}>İlgi geçmişini ve gizlediğin parçaları temizleyip yeniden keşfet. Mağaza takiplerin korunur.</Text></View>
    {!user ? <View style={{ maxWidth: 420, width: '100%', gap: 20, marginTop: 30 }}><View style={[styles.row, { gap: 24, marginBottom: 8 }]}>{(['register', 'login'] as const).map(value => <Pressable key={value} accessibilityRole="tab" accessibilityState={{ selected: mode === value }} onPress={() => { setMode(value); setError(''); }} style={{ paddingVertical: 12, borderBottomWidth: 2, borderBottomColor: mode === value ? colors.ink : 'transparent' }}><Text style={{ fontSize: 15, color: mode === value ? colors.ink : colors.muted }}>{value === 'register' ? 'Hesap oluştur' : 'Giriş yap'}</Text></Pressable>)}</View>{mode === 'register' && <Field label="Adın" placeholder="Ad soyad" value={name} onChangeText={setName} autoComplete="name" />}<Field label="E-posta" placeholder="sen@ornek.com" value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" autoComplete="email" /><Field label="Şifre" placeholder="En az 8 karakter" secureTextEntry value={password} onChangeText={setPassword} autoComplete={mode === 'register' ? 'new-password' : 'current-password'} onSubmitEditing={submit} /><ErrorText message={error} /><Button title={mode === 'register' ? 'Hesabımı oluştur' : 'Giriş yap'} onPress={submit} loading={busy} /><Button title="Şifremi unuttum" outline onPress={() => router.push('/account/forgot-password')} /><Text style={styles.subtitle}>Keşfetmek için hesap gerekmez. Beğendiklerini ve siparişlerini hesabınla yönetebilirsin.</Text></View> : <>
      <NotificationLink key={user.id}/><Button title="Mesajlarda engellediklerin" outline onPress={()=>router.push('/blocked')}/><EmailVerification key={user.id}/><View style={[styles.section, { flexDirection: 'row', justifyContent: 'space-between', flexWrap: 'wrap' }]}><Button title="Çıkış yap" outline onPress={async () => { try { await logout(); setOrders([]); setError(''); } catch (e) { setError((e as Error).message); } }} /></View><ErrorText message={error} /><Text style={{ fontSize: 22, color: colors.ink, fontWeight: '600', marginTop: 30 }}>Siparişlerin</Text>{!orders.length ? <Empty icon="box" title="Henüz siparişin yok" description="Tamamladığın demo siparişler burada görünecek." /> : orders.map(order => <View key={order.id} style={styles.section}><View style={[styles.row, { justifyContent: 'space-between' }]}><View><Text style={{ fontWeight: '600', fontSize: 14, color: colors.ink }}>{order.id}</Text><Text style={{ color: colors.muted, fontSize: 11, marginTop: 6 }}>{new Date(order.createdAt).toLocaleDateString('tr-TR')}</Text></View><Text style={{ fontSize: 10, backgroundColor: colors.pale, color: colors.olive, padding: 7, borderRadius: 4 }}>DEMO SİPARİŞ</Text></View>{order.shipments?.length?order.shipments.map(part=><View key={part.id} style={{gap:6,marginVertical:16}}><Text style={{color:colors.ink,fontWeight:'600'}}>{part.shop} · {shippingLabels[part.status]}</Text>{part.items.map((item,i)=><Text key={i} style={styles.subtitle}>{item.title} · {item.size} · {item.quantity} adet</Text>)}{!!part.carrier&&<Text selectable style={styles.subtitle}>{part.carrier} · {part.trackingNumber}</Text>}{part.updatedAt&&<Text style={styles.subtitle}>Son güncelleme: {new Date(part.updatedAt).toLocaleString('tr-TR')}</Text>}</View>):<Text style={styles.subtitle}>Kargo: {shippingLabels[(order.shipping||emptyShipping).status]}</Text>}{(order.shipments?.length||0)>1&&order.shipping?.updatedAt&&<Text style={styles.subtitle}>Eski sipariş geneli kargo kaydı: {order.shipping.carrier} · {order.shipping.trackingNumber}. Mağaza bazlı bilgiler ayrıca güncellenir.</Text>}{order.items.map((item, i) => <View key={i} style={[styles.row, { justifyContent: 'space-between' }]}><View style={{ flex: 1 }}><Text style={{ fontSize: 14, color: colors.ink }}>{item.title}</Text><Text style={{ fontSize: 11, color: colors.muted, marginTop: 4 }}>{item.shop} · {item.size} · {item.quantity} adet</Text></View><Text style={{ color: colors.ink }}>{money(item.price * item.quantity)}</Text><Pressable accessibilityRole="button" accessibilityLabel={`${item.title} değerlendir`} onPress={() => router.push({ pathname: '/social/[id]', params: { id: item.productId, tab: 'reviews' } })} style={{ paddingVertical: 12 }}><Text style={{ color: colors.olive, fontSize: 11 }}>Değerlendir</Text></Pressable></View>)}<Text style={{ alignSelf: 'flex-end', fontWeight: '600', fontSize: 18, color: colors.ink }}>{money(order.total)}</Text></View>)}
    </>}
  </Page>;
}
